version: "3.9"

services:
  app:
    image: santex-challenge
    ports:
      - "8000:8000"
    command: python manage.py runserver 0.0.0.0:8000
    env_file:
      - .env
    build:
      context: .
      dockerfile: Dockerfile
      args:
        requirement: dev
    volumes:
      - .:/code
    depends_on:
      - db

  db:
    image: postgres:14.5
    restart: always
    ports:
      - "5432:5432"
    env_file:
      - .env
    volumes:
      - postgres_data:/var/lib/postgresql/data

volumes:
  postgres_data:
